In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [9]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
y.shape

(3, 3)

In [11]:
y.ndim

2

In [13]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
y.mean()

5.0

In [15]:
y.mean(axis=1)

array([2., 5., 8.])

In [16]:
y.max(axis=1)

array([3, 6, 9])