In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 学習データを読み込む
train = np.loadtxt('kaiki.csv', delimiter=',', dtype='int', skiprows=1)
train_x = train[:,0]
train_y = train[:,1]

In [3]:
train_x

array([235, 216, 148,  35,  85, 204,  49,  25, 173, 191, 134,  99, 117,
       112, 162, 272, 159, 159,  59, 198])

In [4]:
train_y

array([591, 539, 413, 310, 308, 519, 325, 332, 498, 498, 392, 334, 385,
       387, 425, 659, 400, 427, 319, 522])

In [5]:
# 標準化
mu = train_x.mean()
sigma = train_x.std()
def standardize(x):
    return (x - mu) / sigma

train_z = standardize(train_x)

In [6]:
# パラメータを初期化
theta = np.random.rand(3)

In [7]:
theta

array([0.95929381, 0.76423955, 0.57035743])

In [8]:
# 学習データの行列を作る
def to_matrix(x):
    return np.vstack([np.ones(x.size), x, x ** 2]).T

X = to_matrix(train_z)

# 予測関数
def f(x):
    return np.dot(x, theta)

In [22]:
train_z

array([ 1.39433428,  1.11069026,  0.09554325, -1.59139223, -0.8449606 ,
        0.93154667, -1.38239138, -1.74067856,  0.46875906,  0.73747445,
       -0.11345761, -0.63595975, -0.36724436, -0.44188752,  0.3045441 ,
        1.94669369,  0.25975821,  0.25975821, -1.23310505,  0.84197488])

In [23]:
X

array([[ 1.        ,  1.39433428,  1.94416809],
       [ 1.        ,  1.11069026,  1.23363286],
       [ 1.        ,  0.09554325,  0.00912851],
       [ 1.        , -1.59139223,  2.53252924],
       [ 1.        , -0.8449606 ,  0.71395842],
       [ 1.        ,  0.93154667,  0.8677792 ],
       [ 1.        , -1.38239138,  1.91100592],
       [ 1.        , -1.74067856,  3.02996185],
       [ 1.        ,  0.46875906,  0.21973506],
       [ 1.        ,  0.73747445,  0.54386856],
       [ 1.        , -0.11345761,  0.01287263],
       [ 1.        , -0.63595975,  0.4044448 ],
       [ 1.        , -0.36724436,  0.13486842],
       [ 1.        , -0.44188752,  0.19526458],
       [ 1.        ,  0.3045441 ,  0.09274711],
       [ 1.        ,  1.94669369,  3.78961632],
       [ 1.        ,  0.25975821,  0.06747433],
       [ 1.        ,  0.25975821,  0.06747433],
       [ 1.        , -1.23310505,  1.52054807],
       [ 1.        ,  0.84197488,  0.70892169]])

In [24]:
# 目的関数
def E(x, y):
    return 0.5 * np.sum((y - f(x)) ** 2)

In [25]:
# 学習率
ETA = 1e-3

# 誤差の差分
diff = 1

# 更新回数
count = 0

In [26]:
# 誤差の差分が0.01以下になるまでパラメータ更新を繰り返す
error = E(X, train_y)
while diff > 1e-2:
    # 更新結果を一時変数に保存
    theta = theta - ETA * np.dot(f(X) - train_y, X)

    # 前回の誤差との差分を計算
    current_error = E(X, train_y)
    diff = error - current_error
    error = current_error

    # ログの出力
    count += 1
    log = '{}回目: theta = {}, 差分 = {:.4f}'
    print(log.format(count, theta, diff))

1回目: theta = [9.51170078 2.61932131 9.52305341], 差分 = 152715.5812
2回目: theta = [17.7140057   4.44972045 17.91721916], 差分 = 137493.2255
3回目: theta = [25.5843812   6.25515584 25.78415679], 差分 = 123872.2798
4回目: theta = [33.14001044  8.0353954  33.15344079], 差分 = 111682.1493
5回目: theta = [40.39714142  9.7902527  40.05301316], 差分 = 100770.4727
6回目: theta = [47.37113833 11.51958382 46.50927328], 差分 = 91001.1716
7回目: theta = [54.07653009 13.22328432 52.54716287], 差分 = 82252.7085
8回目: theta = [60.52705623 14.90128646 58.19024624], 差分 = 74416.5311
9回目: theta = [66.73571019 16.55355654 63.46078616], 差分 = 67395.6829
10回目: theta = [72.71478026 18.18009242 68.37981555], 差分 = 61103.5633
11回目: theta = [78.47588834 19.78092117 72.96720516], 差分 = 55462.8195
12回目: theta = [84.03002647 21.35609689 77.24172763], 差分 = 50404.3575
13回目: theta = [89.38759139 22.90569863 81.2211179 ], 差分 = 45866.4584
14回目: theta = [94.5584172  24.42982848 84.92213043], 差分 = 41793.9905
15回目: theta = [99.55180625 25.92860971 88