In [1]:
import numpy as np

In [18]:
ar = np.arange(12).reshape(4,3)
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
ar2 = np.arange(1,13).reshape(3,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.dot(ar, ar2)

array([[ 23,  26,  29,  32],
       [ 68,  80,  92, 104],
       [113, 134, 155, 176],
       [158, 188, 218, 248]])

In [27]:
ar3 = np.zeros(3, dtype = np.int64)
ar3

array([0, 0, 0])

In [43]:
total = np.array([i for i in range(1, 51)])
total

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [44]:
total.sum()

1275

In [45]:
random = np.random.randn(10)
random

array([ 0.19171944,  0.7845939 ,  1.24135981,  2.41665276, -1.96296132,
        1.18821642,  0.01923399,  0.32012842,  0.94991819, -1.00219243])

In [46]:
print(random.min())

-1.9629613219374447


In [47]:
print(random.max())

2.4166527570194227


In [48]:
print( np.sum(random))

4.146669161398176


In [53]:
m = np.ones((5,5), dtype='int')
m

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
m = m *3
m

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])