In [1]:
import numpy as np
from scipy import linalg

In [2]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])
matrix

array([[ 1, -1, -1],
       [-1,  1, -1],
       [-1, -1,  1]])

In [3]:
print("行列式{0}".format(linalg.det(matrix)))

行列式-4.0


In [4]:
print("逆行列{0}".format(linalg.inv(matrix)))

逆行列[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [5]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
eig_value, eig_vector = linalg.eig(matrix)
print("固有値{0}".format(eig_value))
print("固有ベクトル{0}".format(eig_vector))

固有値[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル[[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


In [9]:
from scipy.optimize import newton

In [12]:
def my_function(x):
    return (x**2 + 2*x + 1)

In [17]:
print (newton(my_function,100))
print (newton(my_function,0))

-0.999999979744582
-0.999999985174924


In [18]:
test2 = np.array([[1,2,3],[1,3,2],[3,1,2]])
print("行列式{0}".format(linalg.det(test2)))

行列式-12.000000000000002


In [19]:
eig_value2, eig_vector2 = linalg.eig(test2)
print("固有値{0}".format(eig_value2))
print("固有ベクトル{0}".format(eig_vector2))

固有値[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
固有ベクトル[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [21]:
def test_function(x):
    return (x**3 + 2*x + 1)

In [22]:
print (newton(test_function,0))

-0.45339765151640365
