In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [2]:
%precision 3

'%.3f'

In [4]:
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 前から5つをスライス
sample_array_slice = sample_array[0:5]
sample_array_slice

array([0, 1, 2, 3, 4])

In [11]:
# ３文字まで10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)
# シャローコピーとなっている
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [14]:
# ディープコピー
sample_array_copy = np.copy(sample_array)
sample_array_copy[0:3] = 20
print(sample_array_copy)
print(sample_array)

[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [25]:
# データの準備
sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
# 正規分布の乱数作成　
data = random.randn(5,5)  #平均0、分散1（標準偏差1）
data

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.144,  1.454,  0.761,  0.122,  0.444],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [26]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [27]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [28]:
cond_data = np.array([True, True, False, False, True])
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
np.where(cond_data, x_array, y_array)

array([  1,   2, 300, 400,   5])

In [29]:
sample_names = np.array(['a','b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5,5)

data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [30]:
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [31]:
x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])
cond_data = np.array([False, False, True, True, False])
np.where (cond_data, x_array, y_array)

array([ 6,  7,  3,  4, 10])