In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [3]:
%precision 3

'%.3f'

In [8]:
cond_data = np.array([True, True, False, False, True])
print(np.unique(cond_data))
# ユニバーサル関数
sample_data = np.arange(10)
print(sample_data)
print(np.sqrt(sample_data)) #ルートX

[False  True]
[0 1 2 3 4 5 6 7 8 9]
[0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]


In [7]:
# eのx乗
print(np.exp(sample_data)) 

[1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [15]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('最小値', sample_multi_array_data1.min())
print('最大値', sample_multi_array_data1.max())
print('平均', sample_multi_array_data1.mean())
print('合計', sample_multi_array_data1.sum())

print ('行の合計', sample_multi_array_data1.sum(axis=1))
print ('列の合計', sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値 0
最大値 8
平均 4.0
合計 36
行の合計 [ 3 12 21]
列の合計 [ 9 12 15]


In [19]:
print('Trueが少なくとも１つあるか', cond_data.any())
print('全てTrueかどうか', cond_data.all())

Trueが少なくとも１つあるか True
全てTrueかどうか False


In [20]:
print('5より大きい数字がいくつあるか', (sample_multi_array_data1 > 5).sum())

5より大きい数字がいくつあるか 3


In [22]:
print('対角成分', np.diag(sample_multi_array_data1))
print('対角成分の和', np.trace(sample_multi_array_data1))

対角成分 [0 4 8]
対角成分の和 12


In [24]:
sample_multi_array_data2 = np.arange(16).reshape(4,4)
print(sample_multi_array_data2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
print(np.sqrt(sample_multi_array_data2)) #ルート

[[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [27]:
print(sample_multi_array_data2.max())
print(sample_multi_array_data2.min())
print(sample_multi_array_data2.sum())
print(sample_multi_array_data2.mean())

15
0
120
7.5


In [31]:
print(np.diag(sample_multi_array_data2).sum())
print(np.trace(sample_multi_array_data2))

30
30
