In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [2]:
%precision 3

'%.3f'

In [3]:
sample_array = np.arange(10)

In [4]:
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
np.concatenate([sample_array3,sample_array4], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
np.vstack((sample_array3,sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.hstack((sample_array3,sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [12]:
sample_array_vstack = np.vstack((sample_array3,sample_array4))
sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
first, second, third = np.split(sample_array_vstack,[1,3])
print(first)
print(second)
print(third)

[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]


In [15]:
sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])

In [16]:
sample_array_vstack2 = np.vstack((sample_array3,sample_array4,sample_array5))
first, second, third, forth = np.split(sample_array_vstack2,[2,3,5])
print(first)
print(second)
print(third)
print(forth)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]


In [17]:
print(first)
first.repeat(3)

[[1 2 3]
 [4 5 6]]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [19]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
sample_array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)
sample_array_vstack = np.vstack((sample_array1, sample_array2))
sample_array_vstack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
sample_array_hstack = np.hstack((sample_array1,sample_array2))
sample_array_hstack

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [24]:
sample_list = [1,2,3,4,5]
np.array(sample_list) + 3

array([4, 5, 6, 7, 8])